require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/book_tags", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BookTag. As you add validations to BookTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BookTag.create! valid_attributes
      get book_tags_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      book_tag = BookTag.create! valid_attributes
      get book_tag_url(book_tag)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_book_tag_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      book_tag = BookTag.create! valid_attributes
      get edit_book_tag_url(book_tag)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BookTag" do
        expect {
          post book_tags_url, params: { book_tag: valid_attributes }
        }.to change(BookTag, :count).by(1)
      end

      it "redirects to the created book_tag" do
        post book_tags_url, params: { book_tag: valid_attributes }
        expect(response).to redirect_to(book_tag_url(BookTag.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BookTag" do
        expect {
          post book_tags_url, params: { book_tag: invalid_attributes }
        }.to change(BookTag, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post book_tags_url, params: { book_tag: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested book_tag" do
        book_tag = BookTag.create! valid_attributes
        patch book_tag_url(book_tag), params: { book_tag: new_attributes }
        book_tag.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the book_tag" do
        book_tag = BookTag.create! valid_attributes
        patch book_tag_url(book_tag), params: { book_tag: new_attributes }
        book_tag.reload
        expect(response).to redirect_to(book_tag_url(book_tag))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        book_tag = BookTag.create! valid_attributes
        patch book_tag_url(book_tag), params: { book_tag: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested book_tag" do
      book_tag = BookTag.create! valid_attributes
      expect {
        delete book_tag_url(book_tag)
      }.to change(BookTag, :count).by(-1)
    end

    it "redirects to the book_tags list" do
      book_tag = BookTag.create! valid_attributes
      delete book_tag_url(book_tag)
      expect(response).to redirect_to(book_tags_url)
    end
  end
end
